sudo: required
services:
  - docker
language: bash
script:
  - make shellcheck
  - HYPRIOT_OS_VERSION=${TRAVIS_TAG} make arm64
  - HYPRIOT_OS_VERSION=${TRAVIS_TAG} make armhf
  - HYPRIOT_OS_VERSION=${TRAVIS_TAG} make armhf-raspbian
branches:
  only:
    - master
    - /^v\d.*$/
deploy:
  provider: releases
  skip_cleanup: true
  file:
    - rootfs-armhf-${TRAVIS_TAG}.tar.gz
    - rootfs-arm64-${TRAVIS_TAG}.tar.gz
  on:
    tags: true
    repo: hypriot/os-rootfs
  api_key:
    secure: EMPAsheQaVn8DrLDuh74qmG8I+OVfB5g+dRXp2U55B39NBULHV+nDgjXJR0k4tHnGY9+azsMYkJXziphKQzmpMsFpiNbeBRg0dhWNJyB6V7xIIchxcNiEBc+qhbsDLAeByjoXSLV3IE/bvnQRhTydHqsq60/EetpBTWv/afK03w43AwOBABDiYZonE5HXgrgP0L7CHg4l/hc3KCfisc4SykOqzSmlJ6JD+YZGNWe1cwb5Plf9iardfYn/U3gYpTWhqC19fV6kUNb7mB76TNv4mlbQLnC8/Yie/Z/a+QaSGDQAGzduzxlb2m/5Gbm7BRGN4XD97JdHRIkAuOCEqLsRwzQBfiRX9A5cG/SRHYWomaPh+10+4hx8pwCxvnhHFh4nuDinIkUmxwKpX7HAcq6hVQb0KVBQaZ6qo2tisDlEG4L3HMU/sddae/MA33Nk25Ql3dA67zBDB1Lf/d0Z/9oKDqBwNs8lI4soFM1/cTel3sXwnbIJWROvVOphABc1sGQlRF5HMJZODmVeYag+h4/u/njgA4uW/p8DEbSDT56pHvEfvZdjAl1zrDUJmTP509TsTkfHsBNIjxnAFbCVSgCOD3OdnbuM+5mzoK4foTUZNV0/TjcCY858wKiPE3LZIpZW3G6HtyLbyZ9n7ABsxs48npfSbjpH6umpGiW5IrA9uI=
